# Generated by Django 4.2.4 on 2024-12-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
